spring:
  application:
    name: unicar-api

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

unicar:
  jwt:
    secret: ${JWT_SECRET}
    expiration-ms: ${JWT_EXPIRATION_MS:86400000}

eureca:
  url:
    tokens: ${EURECA_TOKENS_URL:https://eureca.sti.ufcg.edu.br/as-sig/tokens}
    profile: ${EURECA_PROFILE_URL:https://eureca.sti.ufcg.edu.br/as-sig/profile}