package com.unicar.enums;

public enum TipoNotificacao {
    RESERVA_CRIADA,
    RESERVA_ACEITA,
    RESERVA_RECUSADA,
    RESERVA_CANCELADA,
    RESERVA_EXPIRADA,
    CARONA_CANCELADA,
    CARONA_INICIADA,
    CARONA_FINALIZADA,
    NOTIFICACAO_AVALIACAO,
    INTERESSE_TRAJETO
}